-- OAuth 2.1 authorization server, for MCP clients that cannot carry a static bearer token
-- (Claude Desktop and the web app speak OAuth only). Cram is both the authorization server and
-- the resource server; user identity keeps coming from the existing Google login.
--
-- Every secret is stored as a SHA-256 hash, like personal_access_tokens: a database dump must
-- not hand out live credentials.

-- Clients register themselves (RFC 7591) — MCP clients have no way to be provisioned by hand.
CREATE TABLE oauth_clients (
    id            TEXT PRIMARY KEY,                        -- client_id, generated by us
    name          TEXT NOT NULL,
    redirect_uris JSONB NOT NULL,                          -- exact-match list, never prefixes
    scope         TEXT NOT NULL DEFAULT 'read',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at  TIMESTAMPTZ
);

-- A grant is one user's standing consent for one client: what the settings page lists and what
-- "disconnect" revokes. Access and refresh tokens hang off it.
CREATE TABLE oauth_grants (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id    TEXT NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    scope        TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ
);
CREATE INDEX idx_oauth_grants_user ON oauth_grants(user_id);
-- One live grant per (user, client): re-authorizing updates the existing one instead of piling
-- up rows the user would have to revoke one by one.
CREATE UNIQUE INDEX idx_oauth_grants_live ON oauth_grants(user_id, client_id) WHERE revoked_at IS NULL;

-- Authorization codes are single-use and short-lived; PKCE fields are mandatory (OAuth 2.1).
CREATE TABLE oauth_auth_codes (
    code_hash      TEXT PRIMARY KEY,
    client_id      TEXT NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    redirect_uri   TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    scope          TEXT NOT NULL,
    resource       TEXT NOT NULL DEFAULT '',              -- RFC 8707: what the token is for
    expires_at     TIMESTAMPTZ NOT NULL,
    used_at        TIMESTAMPTZ                            -- set on redemption; a second use revokes the grant
);

CREATE TABLE oauth_access_tokens (
    token_hash TEXT PRIMARY KEY,
    grant_id   UUID NOT NULL REFERENCES oauth_grants(id) ON DELETE CASCADE,
    scope      TEXT NOT NULL,
    resource   TEXT NOT NULL DEFAULT '',
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_oauth_access_grant ON oauth_access_tokens(grant_id);

-- Refresh tokens rotate: redeeming one issues a successor and marks this one used. A reuse of a
-- used token means the value leaked, and the whole grant is revoked.
CREATE TABLE oauth_refresh_tokens (
    token_hash TEXT PRIMARY KEY,
    grant_id   UUID NOT NULL REFERENCES oauth_grants(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_oauth_refresh_grant ON oauth_refresh_tokens(grant_id);
