services:
  postgres:
    image: postgres:16
    container_name: cram-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/cram -schemas=public -user=default -password=default migrate
    volumes:
      - ./src/main/resources/db/:/flyway/sql
    depends_on:
      - postgres

volumes:
  pgdata: